# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnaSayfaUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tblwVeriler = QtWidgets.QTableWidget(self.centralwidget)
        self.tblwVeriler.setGeometry(QtCore.QRect(10, 10, 651, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tblwVeriler.setFont(font)
        self.tblwVeriler.setRowCount(250)
        self.tblwVeriler.setColumnCount(2)
        self.tblwVeriler.setObjectName("tblwVeriler")
        self.tblwVeriler.horizontalHeader().setVisible(False)
        self.tblwVeriler.horizontalHeader().setCascadingSectionResizes(False)
        self.tblwVeriler.horizontalHeader().setDefaultSectionSize(300)
        self.tblwVeriler.horizontalHeader().setMinimumSectionSize(39)
        self.tblwVeriler.verticalHeader().setVisible(True)
        self.tblwVeriler.verticalHeader().setDefaultSectionSize(30)
        self.tblwVeriler.verticalHeader().setHighlightSections(True)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(670, 10, 341, 761))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnListele = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnListele.setFont(font)
        self.btnListele.setObjectName("btnListele")
        self.verticalLayout_3.addWidget(self.btnListele)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lneEnAzRating = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneEnAzRating.setFont(font)
        self.lneEnAzRating.setObjectName("lneEnAzRating")
        self.verticalLayout.addWidget(self.lneEnAzRating)
        self.lneAltYil = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneAltYil.setFont(font)
        self.lneAltYil.setObjectName("lneAltYil")
        self.verticalLayout.addWidget(self.lneAltYil)
        self.lneUstYil = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneUstYil.setFont(font)
        self.lneUstYil.setObjectName("lneUstYil")
        self.verticalLayout.addWidget(self.lneUstYil)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 508, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.btnCikis = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCikis.setFont(font)
        self.btnCikis.setObjectName("btnCikis")
        self.verticalLayout_4.addWidget(self.btnCikis)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(820, 780, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.layoutWidget.raise_()
        self.tblwVeriler.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnListele.setText(_translate("MainWindow", "En iyi 250\'yi listele"))
        self.label.setText(_translate("MainWindow", "En az rating puanı:"))
        self.label_2.setText(_translate("MainWindow", "Alt yıl limiti:"))
        self.label_3.setText(_translate("MainWindow", "Üst yıl limiti:"))
        self.btnCikis.setText(_translate("MainWindow", "Uygulamadan çık"))
        self.label_4.setText(_translate("MainWindow", "Designed by Simo Hayha"))

